"""
fetch_scholar.py (ScraperAPI version)

Fetches the Google Scholar author profile page HTML through ScraperAPI
(which handles proxying so Google doesn't block the request), parses the
publication list out of the raw HTML with BeautifulSoup, and writes an HTML
fragment (publications.html) matching this layout for each entry:

    Title (clickable, opens the Google Scholar page for that article in a new tab)
    Authors
    Venue / Journal / Conference info

Environment variables required:
  SCRAPERAPI_KEY - your ScraperAPI API key
  SCHOLAR_ID     - the Google Scholar author id (the 'user=' value in the profile URL)

Output:
  publications.html - an HTML fragment with the publication list
  publications.json - the raw structured data (useful for debugging / future re-use)
"""

import os
import sys
import json
import time
import requests
from bs4 import BeautifulSoup

SCRAPERAPI_KEY = os.environ.get("SCRAPERAPI_KEY")
SCHOLAR_ID = os.environ.get("SCHOLAR_ID")

if not SCRAPERAPI_KEY or not SCHOLAR_ID:
    print("ERROR: SCRAPERAPI_KEY and SCHOLAR_ID environment variables must be set.")
    sys.exit(1)

SCRAPERAPI_ENDPOINT = "http://api.scraperapi.com/"
SCHOLAR_BASE_URL = "https://scholar.google.com/citations"
PAGE_SIZE = 100  # Google Scholar allows up to 100 per page


def fetch_page_html(cstart):
    """Fetches one page of the author's profile via ScraperAPI."""
    target_url = (
        f"{SCHOLAR_BASE_URL}?hl=en&user={SCHOLAR_ID}"
        f"&cstart={cstart}&pagesize={PAGE_SIZE}"
    )
    params = {
        "api_key": SCRAPERAPI_KEY,
        "url": target_url,
    }
    resp = requests.get(SCRAPERAPI_ENDPOINT, params=params, timeout=60)
    resp.raise_for_status()
    return resp.text


def parse_publications(html):
    """Parses the publication rows out of a Google Scholar profile page."""
    soup = BeautifulSoup(html, "html.parser")
    rows = soup.select("tr.gsc_a_tr")

    publications = []
    for row in rows:
        title_tag = row.select_one("a.gsc_a_at")
        if not title_tag:
            continue

        title = title_tag.get_text(strip=True)
        href = title_tag.get("href", "")
        # Links on the profile page are relative (e.g. "/citations?..."),
        # so make them absolute.
        link = f"https://scholar.google.com{href}" if href.startswith("/") else href

        gray_divs = row.select("div.gs_gray")
        authors = gray_divs[0].get_text(strip=True) if len(gray_divs) > 0 else ""
        venue = gray_divs[1].get_text(strip=True) if len(gray_divs) > 1 else ""

        year_tag = row.select_one("span.gsc_a_h")
        year = year_tag.get_text(strip=True) if year_tag else ""

        cited_tag = row.select_one("a.gsc_a_ac")
        cited_by = cited_tag.get_text(strip=True) if cited_tag else ""

        publications.append({
            "title": title,
            "link": link,
            "authors": authors,
            "venue": venue,
            "year": year,
            "cited_by": cited_by,
        })

    return publications


def fetch_all_publications():
    """Loops through pages until no more rows are returned."""
    all_pubs = []
    cstart = 0

    while True:
        print(f"Fetching profile page starting at cstart={cstart}...", flush=True)
        html = fetch_page_html(cstart)
        pubs = parse_publications(html)

        if not pubs:
            break

        all_pubs.extend(pubs)
        print(f"  -> got {len(pubs)} publications (total so far: {len(all_pubs)})", flush=True)

        if len(pubs) < PAGE_SIZE:
            break

        cstart += PAGE_SIZE
        time.sleep(1)  # small pause between pages

    return all_pubs


def build_html(publications):
    """Builds an HTML fragment: title (linked) + authors + venue for each entry."""
    items = []

    def sort_key(p):
        try:
            return -int(p.get("year", 0))
        except (ValueError, TypeError):
            return 0

    for pub in sorted(publications, key=sort_key):
        title = pub.get("title", "Untitled")
        link = pub.get("link", "#")
        authors = pub.get("authors", "")
        venue = pub.get("venue", "")

        item_html = f"""
        <li class="pub-item">
            <a href="{link}" target="_blank" rel="noopener noreferrer" class="pub-title">{title}</a>
            <div class="pub-authors">{authors}</div>
            <div class="pub-venue">{venue}</div>
        </li>"""
        items.append(item_html)

    html = f"""<!-- Auto-generated by fetch_scholar.py — do not edit manually -->
<ul class="publications-list">
{''.join(items)}
</ul>
"""
    return html


def main():
    publications = fetch_all_publications()
    print(f"Fetched {len(publications)} publications total.", flush=True)

    with open("publications.json", "w", encoding="utf-8") as f:
        json.dump(publications, f, ensure_ascii=False, indent=2)

    html = build_html(publications)
    with open("publications.html", "w", encoding="utf-8") as f:
        f.write(html)

    print("Wrote publications.json and publications.html", flush=True)


if __name__ == "__main__":
    main()
